### ISSUE TITLE
Include information on where the source of the quay.io fluentd-elasticsearch docker image is.

### ISSUE THREAD

**Issue by andytson-inviqa** [kokuwaio/helm-charts#20]
Include information on where the source of the quay.io fluentd-elasticsearch docker image is.

**Is your feature request related to a problem? Please describe.**
I would like to see how the docker image is built, and who maintains it, but the quay.io repository contains no information on this

**Describe the solution you'd like**
A link to the docker image's source repository, and if applicable saying who maintains it

**Describe alternatives you've considered**

**Additional context**

**Comment by tpokki** [comment]
It comes from here: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
... and yes, it really took a while to find out where does it come from. 

Also, it would be good that there would be information of the actual fluentd version that is being used, rather than only the fluentd_elasticsearch image version. I.e maybe the charts application version could be combination of image version + fluentd version?

**Comment by monotek** [comment]
It's already there: https://github.com/kokuwaio/helm-charts/blob/main/charts/fluentd-elasticsearch/Chart.yaml#L18
